
server:
  port: 9003

# security:
#   user:
#     name:      admin
#     #   The password is encrypted by this:
#     #   http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_encryption_and_decryption
#     #   the password is 'admin'
#     password: admin

# spring:
#   boot:
#     admin:
#       discovery:
#         management:
#           context-path: ${management.context-path}

# For more details see:
# http://codecentric.github.io/spring-boot-admin/1.4.3/#_securing_spring_boot_admin_server
spring:
  boot:
    admin:
      context-path: /admin
      # discovery:
        # converter.management-context-path: /admin
        # management:
          # context-path: /admin
      # routes:
      #   endpoints: env,metrics,trace,dump,info,configprops,trace,logfile,refresh,heapdump,hystrix.stream
