
server:
  port: 9090

security.basic.enabled: false

eureka:
  instance:
    metadataMap:
      container:
        color: blue

---
spring:
  profiles: zone1
eureka:
  instance:
    metadatMap:
      color: green

server:
  port: 9091

---
spring:
  profiles: zone2
eureka:
  instance:
    metadatMap:
      color: blue