
server:
  port: 9091

security.basic.enabled: false

eureka:
  instance:
    metadataMap:
      container:
        color: green

---
spring:
  profiles: zone1

eureka:
  instance:
    metadataMap:
      container:
        color: blue

server:
  port: 9090

---
spring:
  profiles: zone2

eureka:
  instance:
    metadataMap:
      container:
        color: blue