
server:
  port: 9092

security.basic.enabled: false

eureka:
  instance:
    metadataMap:
      container:
        color: blue

app:
  list:
    - uno
    - dos
    - tres

---
spring:
  profiles: zone1

eureka:
  instance:
    metadataMap:
      container:
        color: green

---
spring:
  profiles: zone2


server:
  port: 9093

eureka:
  instance:
    # status: OUT_OF_SERVICE
    metadataMap:
      container:
        color: blue
