
server:
  port: 9093

security.basic.enabled: false

eureka:
  instance:
    metadataMap:
      container:
        color: blue

---
spring:
  profiles: zone1

eureka:
  instance:
    metadataMap:
      container:
        color: blue

---
spring:
  profiles: zone2


server:
  port: 9092

eureka:
  instance:
    status: OUT_OF_SERVICE
    metadataMap:
      container:
        color: green
