
server:
  port: 9093

security.basic.enabled: false

eureka:
  instance:
    metadataMap:
      version: v2
      container:
        color: blue

app:
  list:
    - uno
    - dos
    - tres

---
spring:
  profiles: zone1

server:
  port: 9092

eureka:
  instance:
    metadataMap:
      version: v1
      container:
        color: green

---
spring:
  profiles: zone2

server:
  port: 9094

eureka:
  instance:
    # status: OUT_OF_SERVICE
    metadataMap:
      version: v3
      container:
        color: blue
